= Changelog
:issue:  https://gitlab.com/ysb33rOrg/terraform-gradle-plugin/issues/
:mr:  https://gitlab.com/ysb33rOrg/terraform-gradle-plugin/merge_requests/

== v0.4.0

// tag::changelog[]
=== Features

* Support backend config for `TerraformInit`.

// end::changelog[]

== v0.3.1

=== Features

* Support for `show` terraform command in the form of `TerraformShowState` task type
* `TerraformPlan` will now also generate a text or JSON-formatted report.

=== Bugs

* {issue}1[#2] - `terraformw`should pick the correct base directory when ran from anywhere within the Gradle project

=== Breaking changes

* Tasks associated with Terraform commands are now prefixed with `tf` instead of `terraform`.


== v0.2.2

=== Features

* Variables can be defined at global, source set and task level. Where variables are the same, values at task level overrides source set and in turn source set overrides global. Task can also specify that source set and global variables can be ignored completely.
* Environment can be defined at global and at task level.
* Support for `validate` and `destroy` terraform commands.

=== Bugs

* {issue}1[#1] - Variables block in source sets are creating accidental sourcesets

== v0.1.3

=== Features

* Bootstrap Terraform without installation
* Terraform source sets
* Support for `init`, `apply`, `plan` and `import` terraform commands.


