= Changelog
:issue:  https://gitlab.com/ysb33rOrg/terraform-gradle-plugin/issues/
:mr:  https://gitlab.com/ysb33rOrg/terraform-gradle-plugin/merge_requests/

== v0.12.0

=== Features

* {issue}60[#60] - Customise backend by source set.

=== Bug fixes

* {issue}62[#62] - Escaped collections within collections of Terraform variables.

=== Deprecations

* `RemoteStateAwsS3ConfigGenerator` has been deprecated in favour of RemoteStateConfigGenerator. Instances of task itself will be empty with a direct dependency on an instance of `RemoteStateConfigGenerator`. Trying to configure the task will display a warning.
* `RemoteStateS3Provider` has been deprecated.

=== Breaking changes

* `TerraformRemoteStateBasePlugin` has been removed and it's functionality absorbed into `TerraformBasePlugin`.
* `AbstractRemoteStateConfigGenerator` has been removed and replaced with `RemoteStateConfigGenerator`.
* When applying the S3 backend, the `remote_state` variable is no longer added by default. In order to do this, set `remote.remoteStateVar = true` on the source set or globally on `terraform.remote.remoteStateVar`.
* `tfstate` is not automatically appended to the key name in `S3` remote state. The default test template has changed to reflect this.
* The default key for `s3` remote state is set to the full project path including the root project name, plus the source set name. This might be different from what your current build is using. If you suddently find that `tfPlan` type tasks are all not finding the resources, then this is probably the culprit. You can choose to manually rename the state object in S3, or you can explicitly set `remote.s3.remoteStateName` to be the one that you have been using.

=== Other

* Default version of Terraform is 1.0.2.

== v0.11.0 / v0.11.1 / v0.11.2

// tag::changelog[]
=== Features

* {issue}11[#11] - `tfStatePull` task implemented
* {issue}44[#44] - Support AWS credentials on Terraform source sets.
* {issue}45[#45] - Support Gitlab credentials on Terraform source sets.
* {issue}54[#54] - Customise values that can be written to S3 backend partial configuration file.
* {issue}55[#55] - Support a text template for S3 backend.

=== Bugs

* {issue}43[#43] - `tfOutput` should not cause `tfApply` or `tfPlan` to be invoked.
* {issue}47[#47] - `tfApply` should pass the `--target/--replace` parameters to `tfPlan`.
* {issue}48[#48] - AWS credentials should not be cached between builds.
* {issue}49[#49] - Truncate log file before task calls Terraform.
$ {issue}51[#51] - Terraform is attempting to create log content in systemroot
* {issue}53[#53] - NPE when running task `tfStatePull`.
* {issue}58[#58] - Default remote prefix needs to take project path into account.
* {issue}59[#59] - Session credentials are not passed to workspace commands.

=== Breaking changes

* `AbstractRemoteStateConfigGenerator.getTemplateResourcePath` is no longer supported as per {issue}55[#55].
* As part of {issue}54[#54], the `RemoteStateS3Provider` interface introduces a new required method called `getAttributesMap`, which could break plugins that are built on top of this suite of plugins.

=== Other

* {issue}56[#56] - `TF_APPEND_USER_AGENT` is added to the terraform execution environment.
* {issue}52[#52] - Added usage example for `getRawOutputVariables`.
* Default version of terraform is `1.0.0`.

// end::changelog[]

== v0.10.0


=== Features

* {issue}16[#16] - Improved up to date checking for various Terraform tasks.
* {issue}25[#25] - File paths printed in console are shown as URIs to support better hyperlinking from IDEs.
* {issue}28[#28] - Remote S3 state can be configured on a per source set basis.
* {issue}29[#29] - Tasks `tfUpgrade` added to aid in upgrading from previous `terraform` sources where the specific version supports it.
* {issue}31[#31] - Tasks `tfFmtCheck` and `tfFmtApply` added.
* {issue}32[#32] - Remove logging levels as it is not supported by Terraform and replace by method `setLogProgress`.
* {issue}33[#33] - Support for terraform 0.15.
* {issue}34[#34] - Support workspaces.
* {issue}35[#35] -Task `tfUntaint` added.
* {issue}36[#36] - `tfApply` tasks now uses the plan generated by `tfPlan`. The latter will be executed if a plan does not exist.
* {issue}37[#37] - Certain features are only enabled for specific terraform versions.
* {issue}38[#38] - On `tfStateRm` and `tfImport`, `--path` has replaced the `--type` and `--name`.
* {issue}39[#39] - `tfPlan` & `tfApply` supports ability to replace resources.
* {issue}40[#40] - task `tfDestroyPlan` added to create a specific destruction plan. `--destroy` parameter on `tfPlan` is no longer supported. Use this new task instead.

=== Bugs

* {issue}41[#41] - `tfDestroy` should not cause `tfApply` to be executed.
* {issue}42[#42] - Skip tasks if no source files in source directory.

=== Other

* Default `terraform` version is `0.15.3`.

== v0.9.0

=== Features

* {issue}22[#22] - `tfInit` can now take `--force-copy` and `--reconfigure` ans command-line options.
* {issue}23[#23] - Support for `terraform output` as `TerraformOutput` task type as well as a provider on the source set that can return all output variables as a deeply nested map.



== v0.8.0 / v0.8.1

=== Features

* {issue}17[#17] - Remote state in S3 simplified.
* {issue}18[#18] - Ability to set destruction plan from command-line.

=== Bugs

* {issue}19[#19] - `createTfS3BackendConfiguration` should run after `generateTerraformConfig`.
* {issue}20[#20] - `remote_state` map is not passed to `terraform`.
* {issue}21[#21] - `Property` and `Provider` instances are not resolved correctly to strings in `VariablesSpec`.

=== Other

* {issue}13[#13] - Remove references to legacy task naming like `terraformXYZ`.
* {mr}17[!17] - `tfShowState` will now use `.tf` extension rather than `.txt`
* Default version of terraform is 0.12.24.


== v0.7.0 / v0.7.1 / v.0.7.2

=== Bugs

* {issue}3[#3] - Task `tfShowState` fails when using remote backend.
* {mr}14[#14] - Remove unnecessary quotes from command line argument.


== v0.6.0

=== Features

* {issue}6[#6] - Bump Terraform version to 0.12.19
* {issue}7[#7] - Use `useAwsEnvironment()` as sort-cut to add all AWS-related environmental variables to Terraform execution environment. Also on non-Windows platforms add `HOME` to Terraform environment.
* {issue}9[#9] - Support for `state mv` terraform command in the form of `TerraformStateMv` task type

=== Breaking changes

* {issue}8[#8] - Instead of ``-configure-backends` use `--no-configure-backends` for a `TerraformInit` task. The task property has also been renamed to `skipConfigureBackends` (from `configureBackend`). This was done becasue a boolean command-line extension does not take a value and rather sets the task property to `true`.


== v0.5.0 / v0.5.1

=== Features

* {issue}5[#5] - Support for `state rm` terraform command in the form of `TerraformStateRm` task type

=== Bugs

* {issue}3[#3] - Task `tfShowState` fails when using remote backend

== v0.4.0

=== Features

* Support backend config for `TerraformInit`.


== v0.3.1

=== Features

* Support for `show` terraform command in the form of `TerraformShowState` task type
* `TerraformPlan` will now also generate a text or JSON-formatted report.

=== Bugs

* {issue}2[#2] - `terraformw`should pick the correct base directory when ran from anywhere within the Gradle project

=== Breaking changes

* Tasks associated with Terraform commands are now prefixed with `tf` instead of `terraform`.


== v0.2.2

=== Features

* Variables can be defined at global, source set and task level. Where variables are the same, values at task level overrides source set and in turn source set overrides global. Task can also specify that source set and global variables can be ignored completely.
* Environment can be defined at global and at task level.
* Support for `validate` and `destroy` terraform commands.

=== Bugs

* {issue}1[#1] - Variables block in source sets are creating accidental sourcesets

== v0.1.3

=== Features

* Bootstrap Terraform without installation
* Terraform source sets
* Support for `init`, `apply`, `plan` and `import` terraform commands.


