= Terraform Gradle Plugin
:imagesdir: images
:icons: font

A collection of Gradle plugins to deal with the Terraform infrastructure management tool in a very gradlesque way.

As of version {revnumber} of this plugin, the minimum supported Gradle version is `{minimum-gradle-version}`. It has also been tested using https://ysb33rorg.gitlab.io/gradleTest[GradleTest] against a wide range of compatibility. The test matrix for this release in addition to `{minimum-gradle-version}` was

.GradleTest version configuration
[source,groovy]
----
include::{includetopdir}/../gradle/plugin-dev.gradle[tags=gradleTestVersions,indent=0]
----

.Support this project
****
If this project is useful to you, you may want to consider donating to the associated https://www.patreon.com/bePatron?u=55368021[Patreon account]
****

Previous versions of the plugin may support older versions of Gradle. See the specific version's documentation for more details.


.Product version documentation
[cols="4*"]
|===
include::{gendocdir}/display-versions.adoc[]
|===

== Other links

* https://gitlab.com/ysb33rOrg/terraform-gradle-plugin[Fork me on GitLab]


////
== Contributors

A special thank you goes to:

* https://github.com/xyz[XYZ] - DESCRIPTION.

If you would like to contribute, please see https://github.com/ysb33r/grolifant/blob/master/HACKING.adoc[HACKING.adoc]
////
