[[RemoteStateS3]]
== Remote state in S3

Storing remote state in S3 seems to be a popular approach with Terraform users. Therefore the `org.ysb33r.terraform.remotestate.s3` plugin adds some conventions to make life easier. Hopefully it the default conventions does nto quite suit your environment, there are enough customisations available.

The plugin adds a `createTfS3BackendConfiguration` tasks and if you have additional Terraform source sets it will add a tasks of the form `createTf<SOUCESET>S3BackendConfiguration`. It also adds a `terraform.remote` and `terraform.remote.s3` extensions. The plugin wil also add a map variable called `remote_state` which contains elements `name`, `aws_region`, `aws_bucket`. If you apply this plugin you will need to add the map variable somewhere in your terraform files.

== Approach

Normally in order for remote state to be used, a set of backend configuraion values or a backend configuration file has to be passed to `terraform init`. In the case of `tfInit` this is done via the `backendConfigValues` and `backendConfigFile` methods. The plugin simplifies this process by generating a configuration file from pre-configured values and a default template. It then automatically configures `tfInit` to use this configuration file.

The default template for creating the configuration is:

[source,terraform]
----
# Default template <1>
include::{resourcesdir}/terraform-gradle-templates/aws-s3-remote-state.tf[]
----
<1> If this is not sufficient for your needs see how to <<CustomiseS3Template>>.

The name of the file in S3 is determine from the project name be default. For each additional sourceset, the name of the sourceset is appended. This makes up the remote state name. This prefix can be modified via the `terraform.remote.prefix` property.

The AWS specifics of bucket name and region is configured via properties in the `terraform.remote.s3` extension.

=== Usage

Add the S3 backend to your Terraform files.

.remote-state.tf
[source,terraform]
----
terraform {
  backend "s3" { // <1>
  }
}

variable "remote_state" { // <2>
    type = map(string)
}
----
<1> Indicate that you play to store remote state in S3.
<2> Allow for Gradle to pass the map of remote state variabled.

If you are interested in using locking of remote state you probably are going to need something like this as well

.remote-state.tf
[source,terraform]
----
data "terraform_remote_state" "aws_tf_remote_state" {
  backend = "s3"
  config = {
    bucket = var.remote_state.aws_bucket // <1>
    key    = "${var.remote_state.name}.tfstate" // <2>
    region = var.remote_state.aws_region // <3>
    encrypt = true
    dynamodb_table = "arn:aws:dynamodb:<REGION>:<ACCOUNT>:table/<TABLENAME>" // <4>
  }
}
----
<1> The name of the bucket where remote state is stored. You can use the `remote_state` map to simplify things. The bucket should pre-exist.
<2> Name of the file in S3 where the state is stored. Convention is to add `.tfstate` to the remote state name.
<3> Region which is used to stored the state.
<4> Your DynamoDB table for storing lock status. The table should pre-exist.

Now tell Gradle about your S3 setup

[source,groovy]
----
terraform {
  remote {
    prefix = 'foo' // <1>

    s3 {
        bucket = 'terraform-managed-remote-state-files' // <2>
        region = 'us-west-1' // <3>
    }
  }
}
----
<1> If you are not happy with the project name being the default prefix for remote state named, then set this here.
<2> Set the S3 bucket that will contain your state files.
<3> Region that you are operating in.

[[CustomiseS3Template,customise the S3 template]]
=== Customising the configuration template

If this is not sufficient for your situation you can supply your own.

[source,groovy]
----
createTfS3BackendConfiguration  {
  templateFile = 'src/tf/mytemplate.tf' // <1>
  beginToken = '##' // <2>
  endToken = '$$' // <3>
  tokens = [   // <4>
    myBucket : 'abc'
  ]
  tokens foo : 'bar' // <5>
}
----
<1> Provide an alternative template file. Anything convertible to a file can be used.
<2> Start delimiter
<3> End delimiter
<4> Replace all default tokens
<5> Add to existing tokens

Substitutions are performed by https://ant.apache.org/manual/api/org/apache/tools/ant/filters/ReplaceTokens.html[Apache Ant's ReplaceTokens].
