== Source Sets

When the `org.ysb33r.terraform` plugin is applied, it adds the `terraformSourceSets` extension which contain the `main` source set. Associated with this source set is the default folder of `src/tf/main` and a number of tasks including:

* `tfApply`
* `tfDestroy`
* `tfImport`
* `tfInit`
* `tfPlan`
* `tfShowState`
* `tfStateMv` (`terraform state mv`)
* `tfStatePush` (`terraform state push`)
* `tfStateRm` (`terraform state rm`)
* `tfValidate`


If additional source sets are needed they can be added by convention i.e.

[source,groovy]
----
terraformSourceSets {
    development // <1>
    staging {
        srcDir = 'staging' // <2>
    }
}
----
<1> Creates a Terraform source set named 'development' with default directory `src/tf/development`
<2> Creates a Terraform source set named 'release` and set the directory to `staging`.

Tasks for additional source sets follow the `tf<SourceSetName><TerraformCommand>` format. For instance in the above example the initialisation task for the `development` source set will be called `tfDevelopmentInit`.

By convention all tasks that map Terraform commands start with `tf`. Other non-commands tasks might start with `terraform` or contain `Terraform` within the task name.