== Terraform variables

A number of Terraform task types support vairtables and files containing variables. Any `variables` block support the following functionality

[source,groovy]
----
variables {
    var 'foo', 'bar' // <1>
    map 'fooMap', foo: 'bar' // <2>
    list 'fooList', 'foo', 'bar' // <3>
    list 'fooList', [ 'foo', 'bar'] // <4>
    file 'filename.tf' // <5>
}
----
<1> Adds one variable called `foo` or value `bar`. The provided value can be anything that can be lazy-evaluated to a string.
<2> Adds a map called `fooMap`. The map keys have to be strings, but the map values can be anything that will lazy-evaluate to a string.
<3> Adds a list called `fooList` with values `foo` and `bar`. THe list entries can be anything that will lazy-evaluate to a string.
<4> Alternative list format
<5> Adds a file containing a list of terraform variables. The name can be anything that will lazy evaluate to a string and may be a relative path. The file will be resolved relative to the source set directory.


There a are a number of ways to define these depending on the context.

On project extension:: When variables are defined on the `terraform` project extension they are visible to all Terraform tasks that want to utilise them.

On source set:: When variables are defined on a specific Terraform source set they are visible to all Terraform tasks that are associated with the specific source set.

On task extension:: When variables are defined on the `terraform` task extension, they are only visible to the specific task. A task extension can also be set up to ignore any variables from the project extension of the associated source set.

[source,groovy]
----
terraform {
    variables {
      var 'foo', 'bar' // <1>
    }
}

terraformSourceSets {
    main {
        variables {
            var 'foo', 'bar' // <2>
        }
    }
}

terraformPlan {
    terraform {
        variables {
            var 'foo', 'bar' // <3>

            global.ignore = true // <4>
            sourceSet.ignore == true // <5>
        }
    }
}
----
<1> Adds a global terraform variable.
<2> Adds a source set-specific terraform variable.
<3> Adds a task-specific terraform variable.
<4> Ignore any global terraform variables.
<5> Ignore any source set-specific terraform variables.

