== Gitlab Credentials
[[GITLAB]]

.Configuring Gitlab credentials
[source,groovy]
----
terraformSourceSets {
    main {
        gitlab {
            useGitlabTokenFromEnvironment() // <1>
            useGitlabTokenFromEnvironment 'production' // <2>
            useProperty 'my.gitlab.token' // <3>
            useProperty 'production', 'my.gitlab.token' // <4>
            clearAllCredentials() // <5>
        }
    }
}
----
<1> Use credentials from environment i.e. the `GITLAB_TOKEN` variable.
This is set to be the default for all workspaces, which are not specifically configured.
<2> Use credentials from the environment for a specific workspace.
<3> Use the value provided by the specific property as the default for all workspaces.
The property is resolved by first looking for a Gradle property by the given name, failing that a System property and finally in the environment.
For the latter the characters are uppercased and the dots replaced with underscores.
For example `my.gitlab.token` will become `MY_GITLAB_TOKEN`.
The property is lazily resolved i.e. only at time of running the specific {terraform} command.
You can use a variant of this method by passing a provider instead of the property name. The provider should provide the specific value.
<4> Use the value provided by the property for a specific workspace.
As with the previous case there is a variant which takes a providersinstead of the property name.
<5> Reset any existing credential configurations.
