[[RemoteStateS3]]
== Remote state in S3

Storing https://www.terraform.io/docs/language/settings/backends/s3.html[remote state in S3] seems to be a popular approach with Terraform users. Therefore the `org.ysb33r.terraform.remotestate.s3` plugin adds some conventions to make life easier. Hopefully it the default conventions does nto quite suit your environment, there are enough customisations available.

The plugin adds a `createTfS3BackendConfiguration` tasks and if you have additional Terraform source sets it will add a tasks of the form `createTf<SOUCESET>S3BackendConfiguration`. It also adds a `terraform.remote` and `terraform.remote.s3` extensions. The plugin wil also add a map variable called `remote_state` which contains elements `name`, `aws_region`, `aws_bucket`. If you apply this plugin you will need to add the map variable somewhere in your terraform files.

=== Approach

Normally in order for remote state to be used, a set of backend configuraion values or a backend configuration file has to be passed to `terraform init`. In the case of `tfInit` this is done via the `backendConfigValues` and `backendConfigFile` methods. The plugin simplifies this process by generating a configuration file from pre-configured values and a default template. It then automatically configures `tfInit` to use this configuration file.

The default template for creating the configuration is:

[source,terraform]
----
# Default template <1>
bucket = "@@bucket_name@@"
key    = "@@remote_state_name@@.tfstate"
region = "@@aws_region@@"
----
<1> If this is not sufficient for your needs see how to <<CustomiseS3Template>>.

The name of the file in S3 is determined from the project name be default. For each additional sourceset, the name of the sourceset is appended. This makes up the remote state name. This prefix can be modified via the `terraform.remote.prefix` property.

The AWS specifics of bucket name and region can be configured via properties in the `terraform.remote.s3` extension, and further cusotmised via the `remote.s3` extension on each source set.

=== Usage

Add the S3 backend to your Terraform files.

.remote-state.tf
[source,terraform]
----
terraform {
  backend "s3" { // <1>
  }
}

variable "remote_state" { // <2>
    type = map(string)
}
----
<1> Indicate that you plan to store remote state in S3.
  You can configure anything as per usual for the https://www.terraform.io/docs/language/settings/backends/s3.html[S3 backend].
<2> Allow for Gradle to pass the map of remote state variables.

Now tell Gradle about your S3 setup.

[[ConfigureRemoteS3]]
.build.gradle
[source,groovy]
----
terraform {
  remote {
    prefix = 'foo' // <1>

    s3 {
        bucket = 'terraform-managed-remote-state-files' // <2>
        region = 'us-west-1' // <3>
        dynamoDbTable = "TerraformLocks" // <4>
    }
  }
}
----
<1> If you are not happy with the project name being the default prefix for remote state named, then set this here.
<2> Set the S3 bucket that will contain your state files.
<3> Region that you are operating in.
<4> The DynamoDB table use for terraform locks.

You can also customise on a per-source set basis.
Such setting will override any values from the global settings.
You can configure nearly any item that is part of the S3 backend via the `remote.s3` extension.
See link:{groovydoc}/remotestate/RemoteStateS3Spec.html[`RemoteStateS3Spec`] for details.

.build.gradle
[source,groovy]
----
terraformSourceSets {
  main {
    remote {
      s3 {
        bucket = 'terraform-managed-remote-state-files' // <1>
      }
    }
  }
}
----
<1> Use a different bucket than what was configured globally

Sometimes you might want to customise two source sets in the same way.
Instead of duplicating the code, you can simply, let the one source set mirror any changes made to another source set using `follow`.

.build.gradle
[source,groovy]
----
terraformSourceSets {
  main {
    remote {
      s3 {
        bucket = 'terraform-managed-remote-state-files'
      }
    }
  }
  staging {
    remote {
      s3.follow(terraformSourceSets.main.remote.s3)  // <1>
    }
  }
}
----
<1> Any changes made to `main` will be reflected in `staging`.

[[CustomiseS3Template,customise the S3 template]]
=== Customising the configuration template

If this is not sufficient for your situation you can supply your own.

[source,groovy]
----
createTfS3BackendConfiguration  {
  templateFile = 'src/tf/mytemplate.tf' // <1>
  textTemplate = """ // <2>
key    = "##remote_state_name$$.tfstate"
region = "##region$$"
  """
  beginToken = '##' // <3>
  endToken = '$$' // <4>
  tokens = [   // <5>
    myBucket : 'abc'
  ]
  tokens foo : 'bar' // <6>
}
----
<1> Provide an alternative template file.
Anything convertible to a file can be used.
<2> Instead of a file, supply an alternative text template.
Anything convertible to a string can be used.
<3> Start delimiter.
<4> End delimiter.
<5> Replace all default tokens.
<6> Add to existing tokens.

Substitutions will be performed by https://ant.apache.org/manual/api/org/apache/tools/ant/filters/ReplaceTokens.html[Apache Ant's ReplaceTokens].

=== Remote state from other source sets

If you are interested in accessing the remote state from another configuration you probably are going to need something like this as well

.remote-state.tf
[source,terraform]
----
data "terraform_remote_state" "aws_tf_remote_state" {
  backend = "s3"
  config = {
    bucket = var.remote_state["bucket"] // <1>
    key    = "${var.remote_state["remote_state_name"]}.tfstate" // <2>
    region = var.remote_state["aws_region"] // <3>
    encrypt = true
    dynamodb_table =  var.remote_state["dynamodb_table"] // <4>
  }
}
----
<1> The name of the bucket where remote state will be stored. You can use the `remote_state` map to simplify things. The bucket should pre-exist.
<2> Name of the file in S3 where the state will be stored. Convention is to add `.tfstate` to the remote state name.
<3> Region which is used to store the state.
<4> Your DynamoDB table for storing lock status. The table should pre-exist.

See https://www.terraform.io/docs/language/state/remote-state-data.html[`terraform_remote_state`] for more details.
