== Terraform Backends

By default, only the https://www.terraform.io/docs/language/settings/backends/local.html[`local`] backend is available.
An <<RemoteStateS3,S3 backend>> can be added via the `org.ysb33r.terraform.remotestate.s3` plugin.

=== Configuring the local backend

Most people using Terraform local state would probably just store `terraform.tfstate` in the same directory as the source and commit that to source control.
In some cases this might not be what you want.
For example you might want to apply terraform to a https://github.com/localstack/localstack[LocalStack] instance and have no need for keeping the state.
The state path can be configured.

[source,groovy]
----
terraformSourceSets {
  main {
    remote {
      local {
        path 'terraform-state/main.tfstate' // <1>
      }
    }
  }
}
----
<1> Set a different path where to store local state.

You can then further configure it to be written to a file.

.build.gradle
[source,groovy]
----
terraformSourceSets {
  main {
    remote {
      local {
        textTemplate = 'path = @@path@@' // <1>
        path 'terraform-state/main.tfstate'
      }
    }
  }
}
----
<1> By default, the template is empty so add a simple template that will set the `path` token from the your setting.

.main.tf
[source,hcl-terraform]
----
terraform {
  backend "local" {}
}
----

=== Configuring a generic backend

If you are using a backend that is not directly supported by this plugin suite, you can still use it by some manipulation of the local backend.

Let's assume you want tho use the https://www.terraform.io/docs/language/settings/backends/consul.html[Consul backend] and it is not supported.

.build.gradle
[source,groovy]
----
terraformSourceSets {
  main {
    remote {
      backend = 'local' // <1>
      local {
        clear() // <2>
        allTokenTemplate() // <3>
        tokens address : "consul.example.com", // <3>
            scheme : "https",
            path : "full/path"
      }
    }
  }
}
----
<1> Ensures that the settings from the `local` backend will be used.
<2> Clear any pre-set tokens.
This set is probably not necessary as the `local` backend does not have any, but it is useful to
<3> Tell Gradle not to use any text tempalte but to simply dump the defined tokens with their values to a backend configuration file.
<4> Define the attributes that you need.

.main.tf
[source,hcl-terraform]
----
terraform {
  backend "consul" {}
}
----

=== How tokens are resolved

If there is no backend defined on a source, the backend of the followed remote state is used. By default, all source sets follow the global remote state settings which, has the `local` set as its default.
If `org.ysb33r.terraform.remotestate.s3` is applied, then the global default will be the S3 backend.

If a backend is defined on the source set, settings will be inherited from a similar backend on the followed remote state even if the followed remote state has not set the specific backend as its default.
This approach allows for global configuration of backends, without activating them all.
Inherited settings are overridden by any local settings on the remote state.

When no backend is defined, and no remote is followed, then the system will act as if a `local` backend is used.

=== Adding a new backend programmatically

If you would like to add another backend via a merge request, then read on.

. Add a class to `src/main/groovy/org/ysb33r/gradle/terraform/remotestate` which extends `AbstractBackendSpec`.
. Add a constructor that takes `org.ysb33r.grolifant.api.core.ProjectOperations`.
. Add setters for all the attributes that is available by the backend. (Use `RemoteStateS3Spec` as an example)
. Configure `defaultTextTemplate` to return something that will be a reasonable default. It is valid to set it to an empty string and leave it to the user to configure as appropriate.
. Add a plugin to `src/main/groovy/org/ysb33r/gradle/terraform/plugins` that will add your new backend specification automatically to the global terraform extension and all terraform source sets. As a minimum in `apply` you will need:

[source,groovy]
----
void apply(Project project) {
  project.pluginManager.apply(TerraformPlugin)
  TerraformBackendExtension.find(project).addBackend('MyBackendName', MySpec) // <1> <2>
}
----
<1> `MyBackendName` is the extension name that will be used as standard. For instance for Consul this could be `consul`.
<1> `MySpec` will be the name of your backend specification. For instance for Consul this could be `ConsulSpec`.