[[TerraformExtension]]
== Terraform extension

The `terraform` project extension configures a method of obtaining a `terraform` executable. On <<platforms,supported platforms>> it offers the option of configuring a Terraform version, which Gradle will then download, cache and use. The project extension also allows for the definition of variables at a global level.

Each Terraform task also has a `terraform` extension which can be used to override any settings from the project extension on a per-task basis.

=== Setting Terraform version

It is possible to select another version of Terraform than the default that the plugin will use.

[source,groovy,role="primary"]
----
terraform {
    executable version : '1.2.3' // <1>
    executable path : '/path/to/terraform' // <2>
}
----
<1> Set new Terraform version
<2> Do not bootstrap Terraform, but rather use the binary at the specified location.

=== Setting Terraform version for source set

Sometimes you might need one of your source sets to run with an older version of Terraform.
For instance, you might want to upgrade, but one of the source sets will take more work and leaving it at an older version for a period might be a good solution.

Assuming that you have sourceSet called `monkey`, this can be achieved via task actions

.build.gradle
[source,groovy]
----
tasks.all { Task t -> // <1>
    if(t.name.startsWith('tfMonkey')) {
        t.terraform.executable version: '1.2.3'
    }
}

import org.ysb33r.gradle.terraform.tasks.AbstractTerraformTask
tasks.withType(AbstractTerraformTask) { AbstractTerraformTask t -> // <2>
    if(t.name startsWith('tfMonkey')) {
        t.terraform.executable version: '1.2.3'
    }
}
----
<1> Using `tasks.all` is a simple solution, especially for groovyDSL.
<2> Using `withType` is an alternative. The typing will help Kotlin DSL users.

